// src/app/(user)/layout.tsx ✅
import type { Metadata } from "next";
import { Lexend, Manrope } from "next/font/google";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/shared/footer/Footer";

const lexend = Lexend({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Add weights you need
  display: "swap",
  variable: "--font-lexend",
});
const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "500"],
  display: "swap",
  variable: "--font-manrope",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`${lexend.variable} ${manrope.variable}`}>
      <Navbar />
      {children}
      <Footer />
    </div>
  );
}
